# Generated by Django 4.2.4 on 2023-10-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subscriber_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Адрес электронной почты'),
        ),
    ]
