# Generated by Django 4.2.4 on 2023-10-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_subscriber_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Адрес электронной почты'),
        ),
    ]
